version: "1.0"

services:
 sonarqube:
  container_name: sonarqube
  image: sonarqube:8.9-community
  volumes:
   - D:\Workspace\Docker\SonarQube\storage\data:/opt/sonarqube/data
   - D:\Workspace\Docker\SonarQube\storage\logs:/opt/sonarqube/logs
   - D:\Workspace\Docker\SonarQube\storage\extensions:/opt/sonarqube/extensions
  ports:
   - 9000:9000
